baseURL = "https://ichochy.com/"
languageCode = "zh-CN"
publishDir = "docs"
title = "回忆中的明天"
summaryLength = 7
theme = "hyde"
uglyurls = true
canonifyURLs = true
hasCJKLanguage = true
disqusShortname = "ichochy"
enableRobotsTXT = false

[outputs]
home = ["HTML", "RSS", "URLS", "ALGOLIA"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[outputFormats.URLS]
mediatype = "text/plain"
baseName = "urls"
isPlainText = true

[outputFormats.ALGOLIA]
mediaType = "application/json"
baseName = "algolia"
isPlainText = true

[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "rss"
isPlainText = true

[params]
postDir = "posts"
layoutReverse = true
themeColor = "theme-base-08"
copyright = "iChochy"
description = "码农小站，写点Java、Swift和感悟"
dateFormat = "2006/01/02"
dateTimeFormat = "2006/01/02 15:04:05"
# caseNo = "沪ICP备19030221号"
# upyun = "https://files.ichochy.com/upyun/upyun.png"
GA_MEASUREMENT_ID = "G-8J2LHY81SL"
adsense = "3691661241035911"
# baiduAnalytics = "6c96b4a33763ee94253645ea9215240b"

[Menus]
main = [
    { Name = "首页", weight = 1, URL = "" },
    { Name = "分类", weight = 2, URL = "/categories.html" },
    { Name = "搜索", weight = 3, URL = "/search.html" },
    { Name = "友链", weight = 4, URL = "/links.html" },
    { Name = "简介", weight = 5, URL = "/about.html" },
    { Name = "站点", weight = 6, URL = "/sites.html" },
    { Name = "VPS", weight = 7, URL = "/vps.html" },
    #     {Name = "标签", weight = 6, URL = "/tags.html"},
#    {Name = "RSS", weight = 8, URL = "/rss.xml"}
]
