baseURL = "https://ichochy.com/"
languageCode = "zh_CN"
publishDir = "docs"
title = "回忆中的明天"
summaryLength = 1
theme = "hyde"
uglyurls = false
hasCJKLanguage = false
disqusShortname = "ichochy"
enableRobotsTXT = false


[outputs]
  home = ["HTML","RSS","TXT"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]

[outputFormats.TXT]
  mediatype = "text/plain"
  isPlainText = true
  baseName = "urls"

[outputFormats.RSS]
  mediatype = "application/xml"
  isPlainText = true
  baseName = "rss"

[params]
  postDir = "posts"
  layoutReverse = false
  copyright = "iChochy"
  description = "码农小站，写点Java、Swift和感悟"
  datetimeFormat = "2006/01/02 15:04:05"
  caseNo = "沪ICP备19030221号"
  adsense = "3691661241035911"
  baiduAnalytics = "6c96b4a33763ee94253645ea9215240b"

[Menus]
  main = [
#      {Name = "Categories", weight = 1, URL = "/categories/"},
#      {Name = "Tags", weight = 2, URL = "/tags/"},
      {Name = "Links", weight = 3, URL = "/links/"},
      {Name = "About", weight = 4, URL = "/about/"},
      {Name = "Feedback", weight = 5, URL = "/feedback/"},
      {Name = "RSS", weight = 6, URL = "/rss.xml"}
  ]
