baseURL = "https://ichochy.com/"
languageCode = "zh-CN"
publishDir = "docs"
title = "回忆中的明天"
summaryLength = 7
theme = "hyde"
uglyurls = true
canonifyURLs = true
hasCJKLanguage = true
disqusShortname = "ichochy"
enableRobotsTXT = false

[outputs]
home = ["HTML", "RSS", "URLS", "ALGOLIA"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]

[outputFormats.URLS]
mediatype = "text/plain"
baseName = "urls"
isPlainText = true

[outputFormats.ALGOLIA]
mediaType = "application/json"
baseName = "algolia"
isPlainText = true

[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "rss"
isPlainText = true

[params]
postDir = "posts"
layoutReverse = true
themeColor = "theme-base-08"
copyright = "iChochy"
description = "码农小站，写点Java、Swift和感悟"
dateFormat = "2006/01/02"
dateTimeFormat = "2006/01/02 15:04:05"
# caseNo = "沪ICP备19030221号"
# upyun = "https://files.ichochy.com/upyun/upyun.png"
GA_MEASUREMENT_ID = "G-8J2LHY81SL"
adsense = "3691661241035911"
# baiduAnalytics = "6c96b4a33763ee94253645ea9215240b"

[Menus]
main = [
    #     {Name = "Tags", weight = 2, URL = "/tags.html"},
    { Name = "Search", weight = 3, URL = "/search.html" },
    { Name = "Categories", weight = 4, URL = "/categories.html" },
    { Name = "About", weight = 5, URL = "/about.html" },
    { Name = "Sites", weight = 6, URL = "/Sites.html" },
    { Name = "Links", weight = 7, URL = "/links.html" },
#    {Name = "RSS", weight = 8, URL = "/rss.xml"}
]
