baseURL = "https://ichochy.com/"
languageCode = "zh-cn"
publishDir = "docs"
title = "回忆中的明天"
summaryLength = 1
theme = "hyde"
DisqusShortname = "ichochy"
uglyurls = false

[params]
  layoutReverse = false
  copyright = "iChochy"
  description = "码农小站，写点Java、Swift和感悟"
  postDir = "posts"
  adsense = "3691661241035911"
  baiduAnalytics = "6c96b4a33763ee94253645ea9215240b"
  caseNo = "沪ICP备19030221号"

[Menus]
  main = [
#      {Name = "Categories", weight = 1, URL = "/categories/"},
#      {Name = "Tags", weight = 2, URL = "/tags/"},
      {Name = "Links", weight = 3, URL = "/links/"},
      {Name = "About", weight = 4, URL = "/about/"}
  ]
