name: Algolia Upload Records

on:
  push:
    branches: [ master ]
env:
  APPLICATION_ID: ${{secrets.APPLICATION_ID}}
  ADMIN_API_KEY: ${{secrets.ADMIN_API_KEY}}
  FILE_PATH: ${{secrets.FILE_PATH}}
  INDEX_NAME: ${{secrets.INDEX_NAME}}
jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: test
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: env
      env:
        iChochy: ${{secrets.ICHOCHY}}
    #- run: npm install algoliasearch
    #- run: node .github/workflows/algolia.js
