# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: export name=mleo
    - run: echo $GITHUB_REPOSITORY
    - run: env
    - run: export APPLICATION_ID=${{secrets.APPLICATION_ID}}
    - run: export ADMIN_API_KEY=${{secrets.ADMIN_API_KEY}}
    - run: export INDEX_NAME=$INDEX_NAME
    - run: export FILE_PATH=${{env.FILE_PATH}}
    - run: npm install algoliasearch
    - run: node .github/workflows/algolia.js
