# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  APPLICATION_ID: ${{secrets.APPLICATION_ID}}
  ADMIN_API_KEY: ${{secrets.ADMIN_API_KEY}}
  FILE_PATH: docs/algolia.json
  INDEX_NAME: iChochy
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: echo ${{env.FILE_PATH}}
    - run: echo $FILE_PATH
    - run: env
    - run: npm install algoliasearch
    - run: node .github/workflows/algolia.js
